# Generated by Django 2.1.1 on 2018-11-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0002_auto_20181013_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='message',
            field=models.CharField(default='hi', max_length=300),
            preserve_default=False,
        ),
    ]
