# Generated by Django 2.1.1 on 2018-11-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0003_snippet_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
